name: Enqueue WHMCS module encoding

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

env:
  PLUGIN_NAME: lkngatewaypreferences
  WORK_DIR: src


jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: '.'
        directory: ${{ env.WORK_DIR }}
        filename: '${{ env.PLUGIN_NAME }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Move .zip to custom location
      run: |
        mkdir -p build
        mv ./src/${{ env.PLUGIN_NAME }}.zip ./build/

    - name: Upload .zip to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }} # Endereço do servidor FTP
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USER }} # Usuário FTP
        password: ${{ secrets.FTP_PASSWORD }} # Senha FTP
        local-dir: ./build/ # Diretório local onde o arquivo está
        server-dir: ./whmcs/ # Diretório remoto onde o arquivo será enviado
        #include: "${{ env.PLUGIN_NAME }}.zip" # Arquivo específico a ser enviado
